print("[Coffee Menu]")
print("1. Amerciano : 1500")
print("2. Cafe Mocha : 2500")
print("3.Green tee latte : 3000", end = '\n');print("")
americano = int(input("Number of americano : "))
cafemocha = int(input("Number of cafe mocha : "))
greenteelatte = int(input("Number of green tee latte : "))
print(" ", end ='\n');print("Total : ",americano * 1500 + cafemocha * 2500 + greenteelatte * 3000)
